# Default configuration
[stations]
selected_profile = "Default"
ignored = []

[stations.profiles.Default]
include = []
exclude = []
priority = ["*_FMP", "*_CTR", "*_APP", "*_TWR", "*_GND"]
frequencies = "ShowAll"
grouping = "FirAndIcao"

# Northern Langen (PADH area and adjacent sectors)
[stations.profiles.Langen_North]
include = [
    "EDGG_*",
    "EDYY_CH*",
    "EDYY_CL*",
    "EDYY_SH*",
    "EDYY_SL*",
    "EDYY_MM*",
    "EDYY_MH*",
    "EDYY_ML*",
    "EDYY_RH*",
    "EDYY_RL*",
    "EDYY_JH*",
    "EDYY_JL*",
    "EDYY_HH*",
    "EDYY_HL*",
    "EDYY_YYD*",
    "EDYY_YO*",
    "EDYY_YN*",
    "EDYY_YL*",
    "EDUU_NTM*",
    "EDUU_FFM*",
    "EDUU_FUL*",
    "EDUU_WUR*",
    "EDUU_HVL*",
    "EDUU_OH2*",
    "EDUU_SLN*",
    "EDUU_TGO*",
    "EDWW_HRZ*",
    "EDWW_EMS*",
    "EDWW_HEI*",
    "EHAA_ACE*",
    "EHMC_MIL*",
    "EHVK_CRS*",
    "EBBU_BN*",
    "EBBU_BW*",
    "EBBU_BE*",
    "EBBU_BH*",
    "EDDG_*",
    "EDDK_*",
    "EDDL_*",
    "EDDF_*_APP",
    "ETOU_*",
    "EDDG_*TWR",
    "EDLP_*TWR",
    "EDLW_*TWR",
    "EDLN_*TWR",
    "EDLV_*TWR"
    ]
exclude = []
priority = [
    "MM_CTR",
    "MH_CTR",
    "ML_CTR",
    "RH_CTR",
    "RL_CTR",
    "SH_CTR",
    "SL_CTR",
    "PADH_CTR",
    "PADL_CTR",
    "CH_CTR",
    "CL_CTR",
    "JH_CTR",
    "JL_CTR",
    "HH_CTR",
    "HL_CTR",
    "FUL_CTR",
    "FFM_CTR",
    "NTM_CTR",
    "OH2_CTR",
    "HVL_CTR",
    "HRZ_CTR",
    "EMS_CTR",
    "HEI_CTR",
    "GIN_CTR",
    "RUD_CTR",
    "HEF_CTR",
    "GED_CTR",
    "SIG_CTR",
    "TAU_CTR",
    "KIR_CTR",
    "EDUU_*_CTR",
    "EDYY_*_CTR",
    "EDGG_*_CTR",
    "EDMM_*_CTR",
    "*_CTR",   
    "DLA_APP",
    "NOR_APP",
    "HMM_APP",
    "PFA_APP",
    "DFDN_APP",
    "DFDS_APP",
    "DFDN_APP",
    "DFDS_APP",
    "*_APP",
    "*_TWR",
    "*_GND"
    ]
frequencies = "ShowAll"
grouping = "None"

# Central Langen (GIN area and adjacent sectors)
[stations.profiles.Langen_North.aliases]
"122.785" = "FUL_CTR"
"132.330" = "FFM_CTR"
"132.080" = "NTM_CTR"
"134.085" = "WUR_CTR"
"120.930" = "SLN_CTR"
"132.405" = "TGO_CTR"
"128.810" = "CH_CTR"
"133.955" = "CL_CTR"
"130.110" = "MM_CTR"
"133.215" = "MH_CTR"
"122.185" = "ML_CTR"
"122.835" = "RH_CTR"
"128.790" = "RL_CTR"
"131.380" = "SH_CTR"
"134.710" = "SL_CTR"
"136.465" = "JH_CTR"
"129.735" = "JL_CTR"
"132.780" = "HH_CTR"
"120.860" = "HL_CTR"
"126.785" = "OH2_CTR"
"128.235" = "HVL_CTR"
"124.730" = "GIN_CTR"
"133.435" = "RUD_CTR"
"127.725" = "HEF_CTR"
"124.430" = "GED_CTR"
"124.900" = "SIG_CTR"
"127.625" = "TAU_CTR"
"133.460" = "KIR_CTR"
"124.240" = "HRZ_CTR"
"125.025" = "EMS_CTR"
"125.855" = "HEI_CTR"
"129.675" = "PFA_APP"
"125.600" = "EIF_APP"
"120.805" = "DFAN_APP"
"125.355" = "DFAS_APP"
"120.155" = "DFDN_APP"
"136.130" = "DFDS_APP"
"135.650" = "PADH_CTR"
"125.225" = "PADL_CTR"
"128.555" = "DLA_APP"
"119.110" = "BOT_APP"
"129.300" = "HMM_APP"
"127.365" = "NOR_APP"
"135.350" = "DKA_APP"

[stations.profiles.Langen_Central]
include = ["EDGG_*",
    "EDUU_NTM*",
    "EDUU_FFM*",
    "EDUU_FUL*",
    "EDUU_WUR*",
    "EDUU_SLN*",
    "EDUU_TGO*",
    "EDYY_CH*",
    "EDYY_CL*",
    "EDYY_SH*",
    "EDYY_SL*",
    "EDYY_MM*",
    "EDYY_MH*",
    "EDYY_ML*",
    "EDYY_RH*",
    "EDYY_RL*",
    "EDYY_YO*",
    "EDYY_YL*",
    "EDWW_HRZ*",
    "EDWW_EMS*",
    "EDWW_HEI*",
    "EDMM_HAL*",
    "EDMM_GER*",
    "EDMM_BBG*",
    "EDMM_HOF*",
    "EDMM_ALB*",
    "EBBU_BW*",
    "EBBU_BE*",
    "EBBU_BH*",
    "EBBU_BL*",
    "LFEE_HE*",
    "LFEE_UE*",
    "LFST_*", 
    "ELLX_*",
    "EDDF_*",
    "EDDS_*_APP",
    "EDDP_*_APP",
    "EDDN_*_APP",
    "EDFH_*",
    "ETOU_*",
    "EDDR_*TWR",
    "EDFE_*TWR"
    ]
exclude = []
priority = [
    "FUL_CTR",
    "FFM_CTR",
    "NTM_CTR",
    "CH_CTR",
    "CL_CTR",
    "MM_CTR",
    "MH_CTR",
    "ML_CTR",
    "SH_CTR",
    "SL_CTR",
    "RH_CTR",
    "RL_CTR",
    "GIN_CTR",
    "RUD_CTR",
    "HEF_CTR",
    "GED_CTR",
    "SIG_CTR",
    "TAU_CTR",
    "KIR_CTR",
    "PADH_CTR",
    "PADL_CTR",
    "HRZ_CTR",
    "EMS_CTR",
    "HEI_CTR",
    "DKB_CTR",
    "BAD_CTR",
    "NKRH_CTR",
    "MAN_CTR",
    "KNG_CTR",
    "KTG_CTR",
    "PSA_CTR",
    "LBU_CTR",
    "EDUU_*_CTR",
    "EDYY_*_CTR",
    "EDGG_*_CTR",
    "EDMM_*_CTR",
    "*_CTR",   
    "PFA_APP",
    "DFDN_APP",
    "DFDS_APP",
    "DFDN_APP",
    "DFDS_APP",
    "DLA_APP",
    "NOR_APP",
    "HMM_APP",
    "STG_APP",
    "REU_APP",
    "*_APP",
    "*_TWR",
    "*_GND"
    ]
frequencies = "ShowAll"
grouping = "None"

# Southern Langen (DKB area and adjacent sectors)
[stations.profiles.Langen_Central.aliases]
"122.785" = "FUL_CTR"
"132.330" = "FFM_CTR"
"132.080" = "NTM_CTR"
"128.810" = "CH_CTR"
"133.215" = "MH_CTR"
"122.835" = "RH_CTR"
"131.380" = "SH_CTR"
"133.955" = "CL_CTR"
"122.185" = "ML_CTR"
"128.790" = "RL_CTR"
"134.710" = "SL_CTR"
"124.730" = "GIN_CTR"
"133.435" = "RUD_CTR"
"127.725" = "HEF_CTR"
"124.430" = "GED_CTR"
"124.900" = "SIG_CTR"
"127.625" = "TAU_CTR"
"133.460" = "KIR_CTR"
"135.650" = "PADH_CTR"
"125.225" = "PADL_CTR"
"125.200" = "DKB_CTR"
"125.680" = "KNG_CTR"
"127.500" = "NKRH_CTR"
"123.280" = "KTG_CTR"
"132.155" = "MAN_CTR"
"125.405" = "PSA_CTR"
"127.050" = "LBU_CTR"
"131.300" = "BAD_CTR"
"124.240" = "HRZ_CTR"
"125.025" = "EMS_CTR"
"125.855" = "HEI_CTR"
"133.615" = "BBG_CTR"
"129.100" = "ALB_CTR"
"133.565" = "HOF_CTR"
"134.800" = "HAB_CTR"
"133.230" = "GER_CTR"
"118.235" = "HAL_CTR"
"125.140" = "NDG_CTR"
"128.555" = "DLA_APP"
"119.110" = "BOT_APP"
"129.300" = "HMM_APP"
"127.365" = "NOR_APP"
"135.350" = "DKA_APP"
"129.675" = "PFA_APP"
"125.600" = "EIF_APP"
"120.805" = "DFAN_APP"
"125.355" = "DFAS_APP"
"120.155" = "DFDN_APP"
"136.130" = "DFDS_APP"
"125.050" = "STG_APP"
"119.200" = "REU_APP"
"129.355" = "NKRL_APP"

[stations.profiles.Langen_South]
include = ["EDGG_*",
    "EDUU_NTM*",
    "EDUU_FFM*",
    "EDUU_FUL*",
    "EDUU_WUR*",
    "EDUU_SLN*",
    "EDUU_TGO*",
    "EDUU_SAL*",
    "EDUU_ERL*",
    "EDUU_CHI*",
    "EDUU_DON*",
    "EDUU_ISA*",
    "EDUU_ALP*",
    "EDYY_HH*",
    "EDYY_HE*",
    "EDMM_HAL*",
    "EDMM_GER*",
    "EDMM_BBG*",
    "EDMM_HOF*",
    "EDMM_ALB*",
    "EDMM_WLD*",
    "EDMM_NDG*",
    "EDMM_SWA*",
    "EDMM_FUE*",
    "EBBU_BW*",
    "EBBU_BE*",
    "EBBU_BH*",
    "EBBU_BL*",
    "LFEE_HE*",
    "LFEE_UE*",
    "LFEE_UH*",
    "LSAS_*",
    "LSAZ_*",
    "LSZH_*_APP",
    "LFST_*", 
    "EDDF_*_APP",
    "EDJA_*_APP",
    "EDDN_*_APP",
    "EDDS_*",
    "EDDR_*TWR",
    "EDSB_*TWR",
    "EDTL_*TWR",
    "EDFM_*TWR"
    ]
exclude = []
priority = [
    "SLN_CTR",
    "WUR_CTR",
    "TGO_CTR",
    "FUL_CTR",
    "FFM_CTR",
    "NTM_CTR",
    "GIN_CTR",
    "RUD_CTR",
    "HEF_CTR",
    "GED_CTR",
    "SIG_CTR",
    "TAU_CTR",
    "KIR_CTR",
    "DKB_CTR",
    "BAD_CTR",
    "NKRH_CTR",
    "MAN_CTR",
    "KNG_CTR",
    "HAB_CTR",
    "KTG_CTR",
    "PSA_CTR",
    "LBU_CTR",
    "ALB_CTR",
    "NDG_CTR",
    "WLD_CTR",
    "FUE_CTR",
    "EDUU_*_CTR",
    "EDYY_*_CTR",
    "EDGG_*_CTR",
    "EDMM_*_CTR",
    "*_CTR",   
    "PFA_APP",
    "DFDN_APP",
    "DFDS_APP",
    "DFDN_APP",
    "DFDS_APP",
    "STG_APP",
    "REU_APP",
    "*_APP",
    "*_TWR",
    "*_GND"
    ]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.Langen_South.aliases]
"122.785" = "FUL_CTR"
"132.330" = "FFM_CTR"
"132.080" = "NTM_CTR"
"134.085" = "WUR_CTR"
"120.930" = "SLN_CTR"
"132.405" = "TGO_CTR"
"124.730" = "GIN_CTR"
"133.435" = "RUD_CTR"
"127.725" = "HEF_CTR"
"124.430" = "GED_CTR"
"124.900" = "SIG_CTR"
"127.625" = "TAU_CTR"
"133.460" = "KIR_CTR"
"129.675" = "PFA_APP"
"125.600" = "EIF_APP"
"125.200" = "DKB_CTR"
"125.680" = "KNG_CTR"
"127.500" = "NKRH_CTR"
"123.280" = "KTG_CTR"
"132.155" = "MAN_CTR"
"125.405" = "PSA_CTR"
"127.050" = "LBU_CTR"
"131.300" = "BAD_CTR"
"133.615" = "BBG_CTR"
"129.100" = "ALB_CTR"
"133.565" = "HOF_CTR"
"134.800" = "HAB_CTR"
"136.525" = "SWA_CTR"
"132.555" = "RDG_CTR"
"133.230" = "GER_CTR"
"118.235" = "HAL_CTR"
"136.230" = "WLD_CTR"
"125.140" = "NDG_CTR"
"133.550" = "FUE_CTR"
"125.050" = "STG_APP"
"119.200" = "REU_APP"
"129.355" = "NKRL_APP"
"129.525" = "FRK_APP"
"120.805" = "DFAN_APP"
"125.355" = "DFAS_APP"
"120.155" = "DFDN_APP"
"136.130" = "DFDS_APP"