[stations.profiles.Default]
include = []
exclude = []
priority = [
    "ED*",
    "E*",
    "L*",
    "B*",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "FirAndIcao"

[stations.profiles.Default.aliases]

[stations.profiles.EDGG_North]
include = [
    "EDGG_*",
    "EDYY_CH*",
    "EDYY_CL*",
    "EDYY_SH*",
    "EDYY_SL*",
    "EDYY_MM*",
    "EDYY_MH*",
    "EDYY_ML*",
    "EDYY_RH*",
    "EDYY_RL*",
    "EDYY_JH*",
    "EDYY_JL*",
    "EDYY_HH*",
    "EDYY_HL*",
    "EDYY_YYD*",
    "EDYY_YO*",
    "EDYY_YN*",
    "EDYY_YL*",
    "EDUU_NTM*",
    "EDUU_FFM*",
    "EDUU_FUL*",
    "EDUU_WUR*",
    "EDUU_HVL*",
    "EDUU_OH2*",
    "EDUU_SLN*",
    "EDUU_TGO*",
    "EDWW_HRZ*",
    "EDWW_EMS*",
    "EDWW_HEI*",
    "EHAA_ACE*",
    "EHMC_MIL*",
    "EHVK_CRS*",
    "EBBU_BN*",
    "EBBU_BW*",
    "EBBU_BE*",
    "EBBU_BH*",
    "EDDG_*",
    "EDDK_*",
    "EDDL_*",
    "EDDF_*_APP",
    "ETOU_*",
    "EDDG_*TWR",
    "EDLP_*TWR",
    "EDLW_*TWR",
    "EDLN_*TWR",
    "EDLV_*TWR",
]
exclude = []
priority = [
    "MM_CTR",
    "MH_CTR",
    "ML_CTR",
    "RH_CTR",
    "RL_CTR",
    "SH_CTR",
    "SL_CTR",
    "PADH_CTR",
    "PADL_CTR",
    "CH_CTR",
    "CL_CTR",
    "JH_CTR",
    "JL_CTR",
    "HH_CTR",
    "HL_CTR",
    "FUL_CTR",
    "FFM_CTR",
    "NTM_CTR",
    "OH2_CTR",
    "HVL_CTR",
    "HRZ_CTR",
    "EMS_CTR",
    "HEI_CTR",
    "GIN_CTR",
    "RUD_CTR",
    "HEF_CTR",
    "GED_CTR",
    "SIG_CTR",
    "TAU_CTR",
    "KIR_CTR",
    "EDUU_*_CTR",
    "EDYY_*_CTR",
    "EDGG_*_CTR",
    "EDMM_*_CTR",
    "*_CTR",
    "DLA_APP",
    "NOR_APP",
    "HMM_APP",
    "PFA_APP",
    "DFDN_APP",
    "DFDS_APP",
    "DFDN_APP",
    "DFDS_APP",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

# Central Langen (GIN area and adjacent sectors)
[stations.profiles.EDGG_North.aliases]
"122.785" = "FUL_CTR"
"132.330" = "FFM_CTR"
"132.080" = "NTM_CTR"
"134.085" = "WUR_CTR"
"120.930" = "SLN_CTR"
"132.405" = "TGO_CTR"
"128.810" = "CH_CTR"
"133.955" = "CL_CTR"
"130.110" = "MM_CTR"
"133.215" = "MH_CTR"
"122.185" = "ML_CTR"
"122.835" = "RH_CTR"
"128.790" = "RL_CTR"
"131.380" = "SH_CTR"
"134.710" = "SL_CTR"
"136.465" = "JH_CTR"
"129.735" = "JL_CTR"
"132.780" = "HH_CTR"
"120.860" = "HL_CTR"
"126.785" = "OH2_CTR"
"128.235" = "HVL_CTR"
"124.730" = "GIN_CTR"
"133.435" = "RUD_CTR"
"127.725" = "HEF_CTR"
"124.430" = "GED_CTR"
"124.900" = "SIG_CTR"
"127.625" = "TAU_CTR"
"133.460" = "KIR_CTR"
"124.240" = "HRZ_CTR"
"125.025" = "EMS_CTR"
"125.855" = "HEI_CTR"
"129.675" = "PFA_APP"
"125.600" = "EIF_APP"
"120.805" = "DFAN_APP"
"125.355" = "DFAS_APP"
"120.155" = "DFDN_APP"
"136.130" = "DFDS_APP"
"135.650" = "PADH_CTR"
"125.225" = "PADL_CTR"
"128.555" = "DLA_APP"
"119.110" = "BOT_APP"
"129.300" = "HMM_APP"
"127.365" = "NOR_APP"
"135.350" = "DKA_APP"

[stations.profiles.EDGG_Central]
include = [
    "EDGG_*",
    "EDUU_NTM*",
    "EDUU_FFM*",
    "EDUU_FUL*",
    "EDUU_WUR*",
    "EDUU_SLN*",
    "EDUU_TGO*",
    "EDYY_CH*",
    "EDYY_CL*",
    "EDYY_SH*",
    "EDYY_SL*",
    "EDYY_MM*",
    "EDYY_MH*",
    "EDYY_ML*",
    "EDYY_RH*",
    "EDYY_RL*",
    "EDYY_YO*",
    "EDYY_YL*",
    "EDWW_HRZ*",
    "EDWW_EMS*",
    "EDWW_HEI*",
    "EDMM_HAL*",
    "EDMM_GER*",
    "EDMM_BBG*",
    "EDMM_HOF*",
    "EDMM_ALB*",
    "EBBU_BW*",
    "EBBU_BE*",
    "EBBU_BH*",
    "EBBU_BL*",
    "LFEE_HE*",
    "LFEE_UE*",
    "LFST_*",
    "ELLX_*",
    "EDDF_*",
    "EDDS_*_APP",
    "EDDP_*_APP",
    "EDDN_*_APP",
    "EDFH_*",
    "ETOU_*",
    "EDDR_*TWR",
    "EDFE_*TWR",
]
exclude = []
priority = [
    "FUL_CTR",
    "FFM_CTR",
    "NTM_CTR",
    "CH_CTR",
    "CL_CTR",
    "MM_CTR",
    "MH_CTR",
    "ML_CTR",
    "SH_CTR",
    "SL_CTR",
    "RH_CTR",
    "RL_CTR",
    "GIN_CTR",
    "RUD_CTR",
    "HEF_CTR",
    "GED_CTR",
    "SIG_CTR",
    "TAU_CTR",
    "KIR_CTR",
    "PADH_CTR",
    "PADL_CTR",
    "HRZ_CTR",
    "EMS_CTR",
    "HEI_CTR",
    "DKB_CTR",
    "BAD_CTR",
    "NKRH_CTR",
    "MAN_CTR",
    "KNG_CTR",
    "KTG_CTR",
    "PSA_CTR",
    "LBU_CTR",
    "EDUU_*_CTR",
    "EDYY_*_CTR",
    "EDGG_*_CTR",
    "EDMM_*_CTR",
    "*_CTR",
    "PFA_APP",
    "DFDN_APP",
    "DFDS_APP",
    "DFDN_APP",
    "DFDS_APP",
    "DLA_APP",
    "NOR_APP",
    "HMM_APP",
    "STG_APP",
    "REU_APP",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

# Southern Langen (DKB area and adjacent sectors)
[stations.profiles.EDGG_Central.aliases]
"122.785" = "FUL_CTR"
"132.330" = "FFM_CTR"
"132.080" = "NTM_CTR"
"128.810" = "CH_CTR"
"133.215" = "MH_CTR"
"122.835" = "RH_CTR"
"131.380" = "SH_CTR"
"133.955" = "CL_CTR"
"122.185" = "ML_CTR"
"128.790" = "RL_CTR"
"134.710" = "SL_CTR"
"124.730" = "GIN_CTR"
"133.435" = "RUD_CTR"
"127.725" = "HEF_CTR"
"124.430" = "GED_CTR"
"124.900" = "SIG_CTR"
"127.625" = "TAU_CTR"
"133.460" = "KIR_CTR"
"135.650" = "PADH_CTR"
"125.225" = "PADL_CTR"
"125.200" = "DKB_CTR"
"125.680" = "KNG_CTR"
"127.500" = "NKRH_CTR"
"123.280" = "KTG_CTR"
"132.155" = "MAN_CTR"
"125.405" = "PSA_CTR"
"127.050" = "LBU_CTR"
"131.300" = "BAD_CTR"
"124.240" = "HRZ_CTR"
"125.025" = "EMS_CTR"
"125.855" = "HEI_CTR"
"133.615" = "BBG_CTR"
"129.100" = "ALB_CTR"
"133.565" = "HOF_CTR"
"134.800" = "HAB_CTR"
"133.230" = "GER_CTR"
"118.235" = "HAL_CTR"
"125.140" = "NDG_CTR"
"128.555" = "DLA_APP"
"119.110" = "BOT_APP"
"129.300" = "HMM_APP"
"127.365" = "NOR_APP"
"135.350" = "DKA_APP"
"129.675" = "PFA_APP"
"125.600" = "EIF_APP"
"120.805" = "DFAN_APP"
"125.355" = "DFAS_APP"
"120.155" = "DFDN_APP"
"136.130" = "DFDS_APP"
"125.050" = "STG_APP"
"119.200" = "REU_APP"
"129.355" = "NKRL_APP"

[stations.profiles.EDGG_South]
include = [
    "EDGG_*",
    "EDUU_NTM*",
    "EDUU_FFM*",
    "EDUU_FUL*",
    "EDUU_WUR*",
    "EDUU_SLN*",
    "EDUU_TGO*",
    "EDUU_SAL*",
    "EDUU_ERL*",
    "EDUU_CHI*",
    "EDUU_DON*",
    "EDUU_ISA*",
    "EDUU_ALP*",
    "EDYY_HH*",
    "EDYY_HE*",
    "EDMM_HAL*",
    "EDMM_GER*",
    "EDMM_BBG*",
    "EDMM_HOF*",
    "EDMM_ALB*",
    "EDMM_WLD*",
    "EDMM_NDG*",
    "EDMM_SWA*",
    "EDMM_FUE*",
    "EBBU_BW*",
    "EBBU_BE*",
    "EBBU_BH*",
    "EBBU_BL*",
    "LFEE_HE*",
    "LFEE_UE*",
    "LFEE_UH*",
    "LSAS_*",
    "LSAZ_*",
    "LSZH_*_APP",
    "LFST_*",
    "EDDF_*_APP",
    "EDJA_*_APP",
    "EDDN_*_APP",
    "EDDS_*",
    "EDDR_*TWR",
    "EDSB_*TWR",
    "EDTL_*TWR",
    "EDFM_*TWR",
]
exclude = []
priority = [
    "SLN_CTR",
    "WUR_CTR",
    "TGO_CTR",
    "FUL_CTR",
    "FFM_CTR",
    "NTM_CTR",
    "GIN_CTR",
    "RUD_CTR",
    "HEF_CTR",
    "GED_CTR",
    "SIG_CTR",
    "TAU_CTR",
    "KIR_CTR",
    "DKB_CTR",
    "BAD_CTR",
    "NKRH_CTR",
    "MAN_CTR",
    "KNG_CTR",
    "HAB_CTR",
    "KTG_CTR",
    "PSA_CTR",
    "LBU_CTR",
    "ALB_CTR",
    "NDG_CTR",
    "WLD_CTR",
    "FUE_CTR",
    "EDUU_*_CTR",
    "EDYY_*_CTR",
    "EDGG_*_CTR",
    "EDMM_*_CTR",
    "*_CTR",
    "PFA_APP",
    "DFDN_APP",
    "DFDS_APP",
    "DFDN_APP",
    "DFDS_APP",
    "STG_APP",
    "REU_APP",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.EDGG_South.aliases]
"122.785" = "FUL_CTR"
"132.330" = "FFM_CTR"
"132.080" = "NTM_CTR"
"134.085" = "WUR_CTR"
"120.930" = "SLN_CTR"
"132.405" = "TGO_CTR"
"124.730" = "GIN_CTR"
"133.435" = "RUD_CTR"
"127.725" = "HEF_CTR"
"124.430" = "GED_CTR"
"124.900" = "SIG_CTR"
"127.625" = "TAU_CTR"
"133.460" = "KIR_CTR"
"129.675" = "PFA_APP"
"125.600" = "EIF_APP"
"125.200" = "DKB_CTR"
"125.680" = "KNG_CTR"
"127.500" = "NKRH_CTR"
"123.280" = "KTG_CTR"
"132.155" = "MAN_CTR"
"125.405" = "PSA_CTR"
"127.050" = "LBU_CTR"
"131.300" = "BAD_CTR"
"133.615" = "BBG_CTR"
"129.100" = "ALB_CTR"
"133.565" = "HOF_CTR"
"134.800" = "HAB_CTR"
"136.525" = "SWA_CTR"
"132.555" = "RDG_CTR"
"133.230" = "GER_CTR"
"118.235" = "HAL_CTR"
"136.230" = "WLD_CTR"
"125.140" = "NDG_CTR"
"133.550" = "FUE_CTR"
"125.050" = "STG_APP"
"119.200" = "REU_APP"
"129.355" = "NKRL_APP"
"129.525" = "FRK_APP"
"120.805" = "DFAN_APP"
"125.355" = "DFAS_APP"
"120.155" = "DFDN_APP"
"136.130" = "DFDS_APP"


[stations.profiles.EDMM_West]
include = [
    "EDMM*",
    "EDXX*",
    "EDYY*",
    "EDUU*",
    "EDWW*",
    "EDGG*",
    "LOVV*",
    "LOWS*_APP",
    "LOWI*_APP",
    "LOWW*_APP",
    "LOWL*_APP",
    "LKAA*",
    "LKPR*_APP",
    "LKKV*_APP",
    "LSAS*",
    "LSZH*_APP",
    "LSFA*_APP",
    "LIPP*",
    "EDDS*_APP",
    "EDDF*_APP",
    "EDDP*_APP",
    "EDDN*_APP",
    "EDDC*_APP",
    "EDDM*",
    "EDDN*",
    "EDJA*",
    "ETSI*",
    "ETSN*",
    "ETSL*",
    "ETHL*",
    "EDMA*",
    "EDMO*",
    "EDMS*",
    "EDME*",
    "ED*_FMP",
    "EP*_FMP",
    "LO*_FMP",
    "LS*_FMP",
    "LI*_FMP",
    "LK*_FMP",
]
exclude = []
priority = [
    "EDMM*",
    "EDDM*",
    "EDDN*",
    "EDGG*",
    "EDDS*",
    "EDUU*",
    "LOVV*",
    "LOWS*",
    "LOWI*",
    "*_FMP",
    "*_CTR",
    "*_DEP",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "Icao"

[stations.profiles.EDMM_West.aliases]

[stations.profiles.EDMM_East]
include = [
    "EDMM*",
    "EDDM*_APP",
    "EDXX*",
    "EDYY*",
    "EDUU*",
    "EDWW*",
    "EDDB*_APP",
    "EDDV*_APP",
    "EDGG*",
    "EDDF*_APP",
    "EPWW*",
    "LKAA*",
    "LKPR*_APP",
    "LKKV*_APP",
    "EDDM*",
    "EDDN*",
    "EDDP*",
    "EDDC*",
    "EDDE*",
    "EDAC*",
    "EDAB*",
    "EDQM*",
    "ETIC*",
    "ETEB*",
    "ETIK*",
    "ED*_FMP",
    "EP*_FMP",
    "LO*_FMP",
    "LS*_FMP",
    "LI*_FMP",
    "LK*_FMP",
]
exclude = []
priority = [
    "EDMM*",
    "EDDP*",
    "EDDN*",
    "EDDC*",
    "EDDE*",
    "EDGG*",
    "EDWW*",
    "EDUU*",
    "*_FMP",
    "*_CTR",
    "*_DEP",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "Icao"

[stations.profiles.EDMM_East.aliases]


[stations.profiles.EDWW]
include = [
    "EDWW*",
    "EDXX*",
    "EDYY*",
    "EDUU_*",
    "EDMM_*",
    "EDGG_*",
    "EHMC_*",
    "EHGG*_APP",
    "EHAA*",
    "EKDK_*",
    "ESMM*",
    "ESMS*_APP",
    "ESAA_*",
    "EPGD_I*_APP",
    "EPWW*",
    "EPSC*_TWR",
    "EPPO*_APP",
    "SCO*",
    "EBBU*",
    "EDDB*",
    "EDDH*",
    "EDDV*",
    "EDDW*",
    "EDAH*",
    "EDHI*",
    "EDHL*",
    "EDVE*",
    "EDVK*",
    "EDXW*",
    "EDAY*",
    "EDAZ*",
    "EDBC*",
    "EDBH*",
    "EDBM*",
    "EDBN*",
    "EDHK*",
    "EDWE*",
    "EDWI*",
    "ETHB*",
    "ETHC*",
    "ETHS*",
    "ETMN*",
    "ETNH*",
    "ETNL*",
    "ETNS*",
    "ETNT*",
    "ETNW*",
    "ETSH*",
    "EDDC*_APP",
    "EDDP*_APP",
    "EDDG*_APP",
    "EDDL*_APP",
    "EDDK*_APP",
    "EDLP*_APP",
    "EDDR*_APP",
    "EDDF*_APP",
    "ED*_FMP",
    "EP*_FMP",
    "EK*_FMP",
    "EH*_FMP",
    "ES*_FMP",
]
exclude = []
priority = [
    "EDWW_*",
    "EDYY_*",
    "EDUU_*",
    "EDGG_*",
    "EDMM_*",
    "*_FMP",
    "*_CTR",
    "*_DEP",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "HideAliased"
grouping = "Icao"

[stations.profiles.EDWW.aliases]
"125.450" = "EPWW_T_CTR"
"125.200" = "EDGG_DKB_CTR"
"133.955" = "EDYY_CL_CTR"
"126.300" = "EPPO_FIS_APP"
"123.390" = "EDUU_CHI_CTR"
"133.805" = "ESMM_XK_CTR"
"133.230" = "EDMM_GER_CTR"
"128.630" = "ESMM_FIS_CTR"
"125.000" = "EBBU_L_CTR"
"135.650" = "EDGG_PAH_CTR"
"128.810" = "EDYY_CH_CTR"
"132.330" = "EDUU_FFM_CTR"
"121.255" = "EPSC_TWR"
"131.300" = "EDGG_BAD_CTR"
"120.540" = "EDDH_HAM_APP"
"132.315" = "EDYY_LH_CTR"
"134.225" = "EDDH_W_APP"
"133.615" = "EDMM_BBG_CTR"
"136.465" = "EDYY_JL_CTR"
"126.900" = "EBBU_I_CTR"
"128.200" = "EBBU_H_CTR"
"136.450" = "EDWW_FLG_CTR"
"135.960" = "EDYY_WST_CTR"
"125.875" = "EDDC_SAS_APP"
"125.750" = "EHAA_LOW_CTR"
"132.405" = "EDUU_TGO_CTR"
"134.800" = "EDGG_HAB_CTR"
"133.460" = "EDGG_KIR_CTR"
"135.530" = "EGPX_CTR"
"125.855" = "EDWW_HEI_CTR"
"133.550" = "EDMM_FUE_CTR"
"129.575" = "EBBU_E_CTR"
"118.205" = "EDDH_A_APP"
"125.025" = "EDWW_EMS_CTR"
"120.805" = "EDDF_N_APP"
"124.900" = "EDGG_SIG_CTR"
"127.365" = "EDDK_NOR_APP"
"136.525" = "EDMM_SWA_APP"
"123.225" = "EDWW_BOR_CTR"
"136.230" = "EDMM_WLD_CTR"
"132.780" = "EDYY_HH_CTR"
"128.355" = "EHMC_MIL_CTR"
"132.635" = "EDMM_TRU_CTR"
"124.405" = "ESMM_4_CTR"
"124.730" = "EDGG_GIN_CTR"
"127.500" = "EDGG_NKH_CTR"
"128.215" = "EKDK_C_CTR"
"126.785" = "EDUU_OH_CTR"
"132.855" = "EDYY_LNH_CTR"
"126.325" = "EDWW_ALR_CTR"
"125.355" = "EDDF_S_APP"
"132.700" = "EPWW_N_CTR"
"134.155" = "ESMS_XL_APP"
"123.625" = "EPWW_R_CTR"
"132.555" = "EDMM_RDG_CTR"
"133.355" = "EDYY_LL_CTR"
"128.790" = "EDYY_RL_CTR"
"128.925" = "EPPO_APP"
"123.280" = "EDGG_KTG_CTR"
"133.860" = "EDUU_SAL_CTR"
"132.755" = "EDYY_NH_CTR"
"119.555" = "EKDK_B_CTR"
"120.860" = "EDYY_HL_CTR"
"129.075" = "EPWW_F_CTR"
"124.625" = "EPWW_J_CTR"
"121.325" = "EGPX_E_CTR"
"129.840" = "EDYY_BB_CTR"
"133.285" = "EDUU_SPE_CTR"
"121.130" = "EDDB_AS_APP"
"126.055" = "EKDK_UV_CTR"
"131.100" = "EBBU_W_CTR"
"120.950" = "EPWW_E_CTR"
"122.185" = "EDYY_ML_CTR"
"118.330" = "EKRN_TWR"
"123.780" = "EKDK_E_CTR"
"132.205" = "EDYY_KL_CTR"
"127.230" = "EBBU_C_CTR"
"123.705" = "EHAA_W_CTR"
"134.980" = "ESMS_L_APP"
"124.155" = "ESMM_7_CTR"
"129.555" = "EDMM_EGG_CTR"
"133.680" = "EDMM_TEG_CTR"
"127.150" = "EPGD_FIS_APP"
"119.110" = "EDDL_BOT_APP"
"124.430" = "EDGG_GED_CTR"
"128.555" = "EDDL_DLA_APP"
"128.235" = "EDUU_HVL_CTR"
"133.215" = "EDYY_MH_CTR"
"127.755" = "ESMM_2_CTR"
"125.225" = "EDLP_PAL_APP"
"127.625" = "EDGG_TAU_CTR"
"129.735" = "EDYY_JH_CTR"
"136.050" = "EDWW_MAR_CTR"
"130.110" = "EDYY_MM_CTR"
"119.490" = "EDDV_HAN_APP"
"126.065" = "EDDP_TRN_APP"
"133.035" = "EDUU_OSE_CTR"
"122.785" = "EDUU_FUL_CTR"
"120.340" = "EDDB_N_DEP"
"134.775" = "EGPX_S_CTR"
"121.380" = "EKDK_I_CTR"
"133.435" = "EDGG_RUD_CTR"
"124.175" = "EDWW_MRZ_CTR"
"130.975" = "EDGG_FMP"
"124.105" = "EKSP_APP"
"124.960" = "EDMM_MEI_CTR"
"120.930" = "EDUU_SLN_CTR"
"136.405" = "EDUU_ERL_CTR"
"134.875" = "EPWW_FIS_CTR"
"135.980" = "EDYY_NL_CTR"
"131.040" = "EKDK_FMP"
"120.630" = "EDDB_S_DEP"
"124.075" = "EDWW_EID_CTR"
"131.380" = "EDYY_SH"
"124.240" = "EDWW_HRZ_CTR"
"119.630" = "EDDB_N_APP"
"133.565" = "EDMM_HOF_CTR"
"124.880" = "EHAA_E_CTR"
"129.100" = "EDMM_ALB_CTR"
"124.555" = "EKDK_L_CTR"
"135.985" = "ESMM_9_CTR"
"135.350" = "EDDK_DKA_APP"
"134.375" = "EHAA_CTR"
"132.080" = "EDUU_NTM_CTR"
"133.155" = "EKDK_D_CTR"
"134.150" = "EDMM_ZUG_CTR"
"134.710" = "EDYY_SL_CTR"
"129.675" = "EDDR_PFA_APP"
"133.755" = "EDUU_ALP_CTR"
"133.475" = "EPWW_C_CTR"
"124.800" = "EDDW_FRI_APP"
"120.305" = "EHGG_APP"
"124.680" = "EKDK_N_CTR"
"126.165" = "EDDP_TRS_APP"
"136.335" = "EDUU_ISA_CTR"
"124.925" = "EPWW_G_CTR"
"132.455" = "EDMM_STA_CTR"
"126.425" = "EDDB_S_APP"
"134.455" = "ESMM_Y_CTR"
"129.925" = "EGPX_H_CTR"
"132.765" = "ESMM_5_CTR"
"136.555" = "EKDK_CTR"
"134.085" = "EDUU_WUR_CTR"
"125.980" = "EBBU_U_CTR"
"135.805" = "ESMM_6_CTR"
"122.835" = "EDYY_RH_CTR"
"130.625" = "EPWW_U_CTR"
"127.865" = "EKDK_UC_CTR"
"127.290" = "EDUU_DON_CTR"
"135.565" = "EKDK_V_CTR"
"125.680" = "EDGG_KNG_CTR"
"136.105" = "EDDB_AN_APP"
"129.300" = "EDDG_HMM_CTR"
"123.850" = "EHAA_S_CTR"
"128.055" = "ESMM_3_CTR"
"135.290" = "EKDK_A_CTR"
"128.805" = "EBBU_H_CTR"
"136.485" = "EKDK_UA_CTR"
"125.405" = "EDGG_PSA_CTR"
"125.140" = "EDMM_NDG_CTR"
"128.180" = "ESMM_8_CTR"
"124.300" = "EHAA_FIS_CTR"
"127.725" = "EDGG_HEF_CTR"
"127.025" = "EPWW_B_CTR"
"131.280" = "ESMM_K_CTR"
"118.235" = "EDMM_HAL_CTR"
"127.050" = "EDGG_LBU_CTR"
"126.825" = "ESAA_CTR_CTR"
"119.605" = "EDDV_A_APP"
